---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: auto-unsealer-not-for-production
rules:
  - apiGroups:
    - ""
    resources:
    - secrets
    verbs:
    - create
    - get
    - delete
