---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: auto-unsealer-not-for-production
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: auto-unsealer-not-for-production
subjects:
- kind: ServiceAccount
  name: default
- kind: ServiceAccount
  name: vault
